"""final state

Revision ID: 35a3a21e8fa9
Revises: 7c40c1e419c3
Create Date: 2026-04-05 19:59:15.759070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35a3a21e8fa9'
down_revision: Union[str, Sequence[str], None] = '7c40c1e419c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('listing_images', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('listing_source_metadata', sa.Column('raw_source_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_source_metadata', 'raw_source_html')
    op.drop_column('listing_images', 'updated_at')
    op.drop_column('listing_images', 'created_at')
    # ### end Alembic commands ###
