"""fix enums

Revision ID: 7c40c1e419c3
Revises: 001
Create Date: 2026-04-05 12:29:21.751428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c40c1e419c3'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_source_metadata', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('listing_source_metadata', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('listings', 'transaction_type',
               existing_type=mysql.ENUM('buy', 'rent'),
               type_=sa.Enum('buy', 'rent', name='transaction_type', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('listings', 'listing_type',
               existing_type=mysql.ENUM('flat', 'house', 'room', 'penthouse', 'duplex'),
               type_=sa.Enum('flat', 'house', 'duplex', 'room', 'penthouse', name='listing_type', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('listings', 'quality_score',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'5'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'quality_score',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'5'"))
    op.alter_column('listings', 'listing_type',
               existing_type=sa.Enum('flat', 'house', 'duplex', 'room', 'penthouse', name='listing_type', native_enum=False, create_constraint=True),
               type_=mysql.ENUM('flat', 'house', 'room', 'penthouse', 'duplex'),
               existing_nullable=False)
    op.alter_column('listings', 'transaction_type',
               existing_type=sa.Enum('buy', 'rent', name='transaction_type', native_enum=False, create_constraint=True),
               type_=mysql.ENUM('buy', 'rent'),
               existing_nullable=False)
    op.drop_column('listing_source_metadata', 'updated_at')
    op.drop_column('listing_source_metadata', 'created_at')
    # ### end Alembic commands ###
